server:
  port: 6381

project:
  name: redisClient
  version: 1.0.0
  description: Redis Client

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制
      max-idle: 8   # 连接池中的最大空闲连接
      min-idle: 0   # 连接池中的最小空闲连接
    timeout: 0      # 链接超时时间
  application:
    name: nacos-redis-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 26380
        dashboard: 127.0.0.1:8080
      eager: true

swagger:
  enabled: true

